### ISSUE TITLE
getting `duplicate: the event already exists` when trying to update PRE

### ISSUE THREAD

**Issue by sebdeveloper6952** [CodyTseng/nostr-relay#20]
I am trying to update a parameterized replaceable event (kind `37515`) with new content but I am getting the message: `duplicate: the event already exists` back from the relay and the event is not updated.

I have created a [failing test case on my fork](https://github.com/sebdeveloper6952/nostr-relay/blob/duplicate-pre/packages/event-repository-sqlite/__test__/event-repository-sqlite.spec.ts) to demonstrate the expected behavior.

**Comment by CodyTseng** [comment]
Thank you very much for discovering this huge mistake 😭 I will fix it as soon as possible.
